version: '3'

services:
  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   container_name: zookeeper
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ALLOW_ANONYMOUS_LOGIN: "yes"
  #   networks:
  #     - kafka-network

  # kafka:
  #   image: bitnami/kafka:latest
  #   container_name: kafkaMQ
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     ALLOW_PLAINTEXT_LISTENER: "yes"
  #     KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
  #     KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
  #   networks:
  #     - kafka-network

  gateway:
    build: ./gateway
    image: datvudinhtrong/gateway
    container_name: gateway
    ports:
      - "3050:3050"
    depends_on:
      - userservices
      - projectservices
      - assignmentservices
      - activityservices
      - departmentservices
      - taskservices
    # networks:
    #   - kafka-network
      
  userservices:
    build: ./userservices
    image: datvudinhtrong/userservices
    container_name: userservices
    environment:
      - PORT=3056
      - EMAIL_PASS="ndnv btjq khen jugp"
      - CLOUDINARY_API_SECRET = Ec2Fdj1v2voufkhhkX-CkhOZnj8
    ports:
      - "3056:3056"
    # networks:
    #   - kafka-network

  departmentservices:
    build: ./departmentservices
    image: datvudinhtrong/departmentservices
    container_name: departmentservices
    ports:
      - "3057:3057"
    # networks:
    #   - kafka-network

  assignmentservices:
    build: ./assignmentservices
    image: datvudinhtrong/assignmentservices
    container_name: assignmentservices
    environment:
      - PORT=3058
    ports:
      - "3058:3058"
    # networks:
    #   - kafka-network

  projectservices:
    build: ./projectservices
    image: datvudinhtrong/projectservices
    container_name: projectservices
    environment:
      - PORT=3059
      - CLOUDINARY_API_SECRET = Ec2Fdj1v2voufkhhkX-CkhOZnj8
    ports:  
      - "3059:3059"
    # networks:
    #   - kafka-network

  taskservices:
    build: ./taskservices
    image: datvudinhtrong/taskservices
    container_name: taskservices
    environment:
      - PORT=3060
      - CLOUDINARY_API_SECRET = Ec2Fdj1v2voufkhhkX-CkhOZnj8
    ports:
      - "3060:3060"
    # networks:
    #   - kafka-network

  activityservices:
    build: ./activityservices
    image: datvudinhtrong/activityservices
    container_name: activityservices
    environment:
      - PORT=3061
    ports:
      - "3061:3061"
    # networks:
    #   - kafka-network

# networks:
#   kafka-network:
#     driver: bridge
