version: "3.8"

services:
  projectmanagerui:
    build: ./projectmanagerui
    image: datvudinhtrong/projectmanagerui
    container_name: projectmanagerui
    environment:
      - PORT=3000
  gateway:
    build: ./gateway
    image: datvudinhtrong/gateway
    container_name: gateway
    ports:
      - "3050:3050"
    depends_on:
      - userservices
      - projectservices
      - assignmentservices
      - activityservices
      - departmentservices
      - taskservices
    networks:
      - kafka-network
  userservices:
    build: ./userservices
    image: datvudinhtrong/userservices
    container_name: userservices
    environment:
      - PORT=3056
      - EMAIL_PASS="ndnv btjq khen jugp"
      - CLOUDINARY_API_SECRET=Ec2Fdj1v2voufkhhkX-CkhOZnj8
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=...
    ports:
      - "3056:3056"
    depends_on:
      - kafka
    networks:
      - kafka-network

  departmentservices:
    build: ./departmentservices
    image: datvudinhtrong/departmentservices
    container_name: departmentservices
    environment:
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=...
    ports:
      - "3057:3057"
    depends_on:
      - kafka
    networks:
      - kafka-network

  assignmentservices:
    build: ./assignmentservices
    image: datvudinhtrong/assignmentservices
    container_name: assignmentservices
    environment:
      - PORT=3058
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=...
    ports:
      - "3058:3058"
    depends_on:
      - kafka
    networks:
      - kafka-network

  projectservices:
    build: ./projectservices
    image: datvudinhtrong/projectservices
    container_name: projectservices
    environment:
      - PORT=3059
      - CLOUDINARY_API_SECRET=Ec2Fdj1v2voufkhhkX-CkhOZnj8
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=...
    ports:
      - "3059:3059"
    depends_on:
      - kafka
    networks:
      - kafka-network

  taskservices:
    build: ./taskservices
    image: datvudinhtrong/taskservices
    container_name: taskservices
    environment:
      - PORT=3060
      - CLOUDINARY_API_SECRET=Ec2Fdj1v2voufkhhkX-CkhOZnj8
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=...
    ports:
      - "3060:3060"
    depends_on:
      - kafka
    networks:
      - kafka-network

  activityservices:
    build: ./activityservices
    image: datvudinhtrong/activityservices
    container_name: activityservices
    environment:
      - PORT=3061
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=...
    ports:
      - "3061:3061"
    depends_on:
      - kafka
    networks:
      - kafka-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - kafka-network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafkaMQ
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafkaMQ:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
    networks:
      - kafka-network
    depends_on:
      - zookeeper
volumes:
  esdata:
    driver: local

networks:
  kafka-network:
    driver: bridge
